# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-18 10:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='public_key',
            field=models.TextField(default=''),
        ),
    ]
